# see https://jekyllrb.com/docs/configuration/

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Flexible Framework
description: >- # this means to ignore newlines until "baseurl:"
  Aleks Hughes's personal blog on Python, R, Data Science and maths
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flexibleframework.xyz" # the base hostname & protocol for your site, e.g. http://example.com
email: aleks.hughes@gmail.com
author:
  name: Aleks Hughes
  twitter: alekshug
  picture: /assets/IMG-20180805-WA0012.jpg
twitter_username: alekshug
github_username:  w0rdsm1th
future: true  # allows future dated posts
search: true  # allows site wide search https://github.com/mmistakes/jekyll-theme-basically-basic#search
# pygments unsupported with github, only supports
# highlighter: pygments  # https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
permalink: /:year/:month/:title/

copyright: "built using Jekyll and the Basically Basic theme. Content copyright Aleks Hughes 2019"

# over rides navigation area appearance and ordering https://github.com/jekyll/minima
# for https://github.com/mmistakes/jekyll-theme-basically-basic#github-pages-method
# set in  /_data/theme.yml as navigation_pages
# header_pages:
#   - about.md

# defaults:
#  -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#       layout: "default"

plugins:
  - jekyll-feed

exclude:
    - posts_materials/*
    - notes.txt
    - .gitignore
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Gems - paginate from css wizardry and rest from https://help.github.com/articles/configuring-jekyll-plugins/
# gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jemoji]
